"""add stock_batch table

Revision ID: 255711bb63b1
Revises: 49fb4d0375c9
Create Date: 2026-05-16 08:50:08.754407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255711bb63b1'
down_revision = '49fb4d0375c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('qty_original', sa.Float(), nullable=False),
    sa.Column('building', sa.String(length=20), nullable=False),
    sa.Column('location_detail', sa.String(length=200), nullable=True),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('received_by', sa.String(length=10), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_batches')
    # ### end Alembic commands ###
