"""add notes to materials

Revision ID: 49fb4d0375c9
Revises: bbe8e08ae019
Create Date: 2026-05-09 09:04:30.875264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49fb4d0375c9'
down_revision = 'bbe8e08ae019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
