"""add payment_terms to customer

Revision ID: 6d3c2d4d8c1f
Revises: f2e8e4cafcf8
Create Date: 2026-05-19 09:52:39.874585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d3c2d4d8c1f'
down_revision = 'f2e8e4cafcf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_terms', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('payment_terms')

    # ### end Alembic commands ###
