"""multi-level bom and production routing

Revision ID: c6a64c110b8f
Revises: a1c4e7b2f9d0
Create Date: 2026-06-03 20:41:48.374012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a64c110b8f'
down_revision = 'a1c4e7b2f9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('machine_type', sa.String(length=40), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('requires_machine', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('operation_machines',
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.PrimaryKeyConstraint('operation_id', 'machine_id')
    )
    op.create_table('product_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('daily_output', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('product_operation_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('planned_start', sa.Date(), nullable=False),
    sa.Column('planned_end', sa.Date(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('actual_start', sa.Date(), nullable=True),
    sa.Column('actual_end', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['product_operation_id'], ['product_operations.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bom_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('component_product_id', sa.Integer(), nullable=True))
        batch_op.alter_column('material_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_bom_component_product', 'products', ['component_product_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_subassembly', sa.Boolean(), nullable=True))

    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_wo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_work_order_parent', 'work_orders', ['parent_wo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_work_order_parent', type_='foreignkey')
        batch_op.drop_column('parent_wo_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_subassembly')

    with op.batch_alter_table('bom_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bom_component_product', type_='foreignkey')
        batch_op.alter_column('material_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('component_product_id')

    op.drop_table('production_tasks')
    op.drop_table('product_operations')
    op.drop_table('operation_machines')
    op.drop_table('operations')
    op.drop_table('machines')
    # ### end Alembic commands ###
