"""add delivery_note status

Revision ID: f2e8e4cafcf8
Revises: 255711bb63b1
Create Date: 2026-05-16 09:07:07.267064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e8e4cafcf8'
down_revision = '255711bb63b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_notes', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
